source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'ApplozicCocoaPodDemo' do
    # Add use_frameworks for applozic
    use_frameworks!
    pod 'Applozic', "~> 7.13.0"
  # Pods for ApplozicCocoaPodDemo

  target 'ApplozicCocoaPodDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplozicCocoaPodDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
