platform :ios, '9.0'

target 'ApplozicCocoaPodDemo' do
    # Add use_frameworks for applozic
    use_frameworks!
    pod 'Applozic'
  # Pods for ApplozicCocoaPodDemo

  target 'ApplozicCocoaPodDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplozicCocoaPodDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
