source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'ApplozicCocoaPodDemo' do
    # Add use_frameworks for applozic
    use_frameworks!

  # Pods for ApplozicCocoaPodDemo
  pod 'Applozic'

  target 'ApplozicCocoaPodDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplozicCocoaPodDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
